language: node_js

node_js:
    - "stable"

install:
  - npm install
before_script:
  - export CI=false
  
scripts:
  - npm run test
  - npm run build

cache:
  directories: 
    - npm: true
    - yarn: true
    - packages/create-react-app/node_modules
    - packages/react-scripts/node_modules