/*******************  McAfee CONFIDENTIAL AND PROPRIETARY  **************************
*
*  Copyright (c) 2017 McAfee Inc.  All Rights Reserved.
*
*  This file and the information contained herein is the confidential and
*  proprietary information of Intel Corporation.  Your rights to this file and its
*  information are subject to the terms of the license agreement between
*  Intel Corporation and you or your company.
*
********************  McAfee CONFIDENTIAL AND PROPRIETARY  **************************/

mcafee_wa_annotationoptions={Unknown:-1,None:1,OnlySecureSearch:2,All:4};
var mcafee_wa_bkconstants={uninstallUrl:"https://home.mcafee.com/root/landingpage.aspx?lpname=get-it-now",siteAdvisorUrl:"http://www.siteadvisor.com/",siteAdvisorUrlSecure:"https://www.siteadvisor.com/",siteReportUrl:"https://www.mcafee.com/threat-intelligence/site/default.aspx?url=",blockPageUrl:"https://www.siteadvisor.com/restricted.html",phishingPageUrl:"https://www.siteadvisor.com/phishing.html",maxCacheRecords:1E3,browsertype:"browsertype",useragent:"useragent",whitelistUrl:"about:blank?command=whitelist&token=1",
domain:"domain",redirectURL:"redirectURL",originalURL:"originalURL",chromeExtensionVersion:"chromeExtVer",disabled:"disabled",notchromecompliant:"SearchExtensionDisabled",viewport:"viewport",annonlyonssearch:"*OnlyShowAnnotationsOnSecureSearch",showicons:"*Icons",pnaclenabled:"Pnaclenabled",phishingcategory:169,pprotectfeaturedisabled:"*FeatureDisablePasswordCheck",userdisabledpprotect:"*UserOptionDisablePasswordCheck",SystemGEO:"SystemGEO",BingCountrySet:"BingCountrySet",ProviderForced:"ProviderForced",
BingQString:"PC=MC",BingProvider:23,cookie:"Cookie",maxreservedcallbackid:5};mcafee_wa_browsertypes={Unknown:-1,Firefox:1,Chrome:2,McAfeeSecureBrowser:3,Opera:4,Edge:5,Agnostic:6};function mcafee_wa_cache(){}mcafee_wa_cache.prototype.set=function(a,b){};mcafee_wa_cache.prototype.get=function(a){};mcafee_wa_color={SA_Green:0,SA_Yellow:1,SA_Red:2,SA_Unknown:3,SA_HackerSafe:4,SA_Cashback:5,SA_Disabled:6};
var mcafee_wa_commands={dssrequest:"dssrequest",reportstat:"reportstat",executecommand:"executecommand",ondoccomplete:"ondoccomplete",onnavigateiframe:"onnavigateiframe",onredirectiframe:"onredirectiframe",onnavigate:"onnavigate",onoptionreceived:"onoptionreceived",setoption:"setoption",getsupportedfeatures:"getsupportedfeatures",isframeblocked:"isframeblocked",whitelistediframe:"whitelistediframe",ispageblocked:"ispageblocked",logmsg:"logmsg",getxyviewport:"getxyviewport",getres:"getres",showoptions:"showoptions",
addpagescanstat:"addpagescanstat",getbingsecuresearchenabled:"getbingsecuresearchenabled"},mcafee_wa_disabledflags={disabledChrome:1,disabledSafeBrowser:2,disabledFirefox:4,disabledEdge:8,disabledOpera:16};mcafee_wa_executecommands={showsettingsdialog:1,checkpassword:2,raisenewtabevent:3,showwelcomemessage:4};mcafee_wa_extensionmsgs={setoptionstring:1,sendtelemetry:2,ping:3,syncoptionsfrommain:4};mcafee_wa_extensiontypes={Unknown:-1,Main:0,Search:1};
var mcafee_wa_jscommands={addbitmap:"addBitmap",addcontexttomap:"addContextToMap",addctxref:"addCtxRef",addurlhash:"addUrlHash",changebitmap:"changeBitmap",geturlhash:"getUrlHash",idfromcontext:"idFromContext",navigate:"navigate",removectxref:"removeCtxRef",tryaddpasswordhandler:"tryAddPasswordHandler",urlfromcontext:"urlFromContext",getxyviewport:"getxyviewport",refreshsettings:"refreshSettings"},mcafee_wa_loggertype={defaultLogger:0,nativeLogger:1};mcafee_wa_logtypes={None:0,Info:1,Err:2,All:3};
var mcafee_wa_nativecommands={activate:"activate",ondownloadfinished:"onDownloadFinished",reportstat:"reportStat",ondssrequest:"onDssRequest",onbeforenavigate:"onBeforeNavigate",onnavigate:"onNavigate",ondoccomplete:"onDocComplete",executecommand:"executeCommand",onMenuItemClick:"onMenuItemClick",setsystemoptionstring:"setSystemOptionString",getsystemoptionstring:"getSystemOptionString",getsystemoptionbool:"getSystemOptionBool",getsystemoptionint:"getSystemOptionInt",onCSync:"onCSync",logmsg:"logMsg"};
function mcafee_wa_onbeforesendheaderlistener(){}mcafee_wa_onbeforesendheaderlistener.prototype.init=function(){};function mcafee_wa_promise(){this.pThis=this.commandParams=this.command=this.promise=this.reject=this.resolve=null}mcafee_wa_promise.prototype.createPromise=function(a,b,c,d,e,f){this.resolve=b;this.reject=c;this.command=d;this.commandParams=e;this.pThis=f;return this.promise=new Promise(a)};mcafee_wa_scorevals={ScoreMinimal:15,ScoreUnknown:30,ScoreMedium:50};
var mcafee_wa_searchoption={securesearch:1,anysearch:2,nosearch:0},mcafee_wa_supportedfeatures={none:0,annotations:1,blockpages:2,iframeblocking:4,pprotection:8},mcafee_wa_telemetrycounters={incrstatsrchitunk:"INCREMENTSTAT_SearchHit_Unknown_",incrstat:"INCREMENTSTAT_",browsererr:"BrowserError"},mcafee_wa_uriparser=function(){return{getParam:function(a,b){var c=a.indexOf("?");if(-1==c)return null;for(var c=a.substring(c+1).split("&"),d=0;d<c.length;++d){var e=c[d].indexOf("=");if(-1!=e&&c[d].substring(0,
e)==b)return c[d].substring(e+1)}return null},getURI:function(a){var b=a.split("?");return 2>b.length&&(hashParts=a.split("#"),2<=hashParts.length)?hashParts[0]:b[0]}}}(),mcafee_wa_browsertypefinder=function(){return{getBrowserType:function(a){return a==mcafee_wa_browsertypes.Chrome&&/Secure\//.test(navigator.userAgent)?mcafee_wa_browsertypes.McAfeeSecureBrowser:a},browserTypeToString:function(a){switch(a){case 1:return"FF";case 2:return"CH";case 3:return"MSB";case 4:return"OP";case 5:return"ED";
case 6:return"AG"}return"UN"}}}();function mcafee_wa_logger(){this._logTypes=mcafee_wa_logtypes.None}mcafee_wa_logger.prototype.SetLogTypes=function(a){this._logTypes=a};mcafee_wa_logger.prototype.log=function(a){mcafee_wa_logtypes.Info&this._logTypes&&console.log((new Date).toLocaleString()+" "+a)};mcafee_wa_logger.prototype.error=function(a){mcafee_wa_logtypes.Err&this._logTypes&&console.error((new Date).toLocaleString()+" "+a)};
var mcafee_wa_supportedextensions=function(){return{isExtensionSupported:function(a){return"lalnlkdjolkfkfgaicmnjegcfeelnhkj"==a||"lmjfclhkpjjgloekikcgameicbjbgpjg"==a||"fheoggkfdfchfphceeifdbepaooicaho"==a?!0:!1},getBuddyExtensions:function(){var a=[];mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?(a.push("lalnlkdjolkfkfgaicmnjegcfeelnhkj"),a.push("lmjfclhkpjjgloekikcgameicbjbgpjg")):a.push("fheoggkfdfchfphceeifdbepaooicaho");return a}}}(),mcafee_wa_globals=function(){var a=new mcafee_wa_logger,
b=new Map;return{uid:"{0DE9E47C-871A-4F90-8440-B190C216800A}",resourceRequestor:null,dssRequestor:null,resourceRootURI:null,annotationProperties:null,balloonProperties:null,reputationReqCount:10,annotationEvents:null,activeBalloonElement:null,debugMode:!1,logger:a,activeURI:null,mapSelectors:b,cacheStats:{},imageCounter:0,eventHandler:null,debugTitle:"",onlyShowMcAfeeSecure:!1,isBingSecureSearchEnabled:!1}}();function mcafee_wa_resourcerequestor(){this._messages=null}
mcafee_wa_resourcerequestor.prototype.getURI=function(a){var b=null;return b=null!=mcafee_wa_globals.resourceRootURI?mcafee_wa_globals.resourceRootURI+a:chrome.extension.getURL(a)};
mcafee_wa_resourcerequestor.prototype.getImage=function(a,b){try{var c=new XMLHttpRequest,d=this.getURI("images/"+a);c.open("GET",d,!0);c.responseType="blob";c.onload=function(a){if(4==c.readyState&&200==c.status){var d=new FileReader;d.onloadend=function(){b(d.result)};d.readAsDataURL(c.response)}};c.onerror=function(b){mcafee_wa_globals.logger.error("Failed in requesting html: "+a+b)};c.send(null)}catch(e){mcafee_wa_globals.logger.error(e)}};
mcafee_wa_resourcerequestor.prototype.getContent=function(a,b,c){try{var d=new XMLHttpRequest,e=this.getURI(b+a);d.open("GET",e,!0);"json/"==b&&d.overrideMimeType("application/json");d.onload=function(a){4==d.readyState&&200==d.status&&c(d.responseText)};d.onerror=function(b){mcafee_wa_globals.logger.error("Failed in requesting :"+a+b)};d.send(null)}catch(f){mcafee_wa_globals.logger.error(f)}};mcafee_wa_resourcerequestor.prototype.getJSON=function(a,b){this.getContent(a,"json/",b)};
mcafee_wa_resourcerequestor.prototype.getHtml=function(a,b){this.getContent(a,"html/",b)};mcafee_wa_resourcerequestor.prototype.getResStr=function(a,b){if(null!=mcafee_wa_globals.resourceRootURI){var c=this;null==this._messages?this.getContent("messages.json","_locales/"+window.navigator.language,function(d){null!=d&&(c._messages=JSON.parse(d),null!=c._messages&&b(c._messages[a].message))}):b(c._messages[a].message)}else{var d=chrome.i18n.getMessage(a);"??"==d&&(d="");b(d)}};
var mcafee_wa_msgdispatchhelper=function(){return{toQualifiedImagePath:function(a){a=a.startsWith("small_")?"images/"+a:"images/small_"+a;return(new mcafee_wa_resourcerequestor).getURI(a)}}}(),mcafee_wa_settings={loggertype:mcafee_wa_loggertype.defaultLogger,logtype:mcafee_wa_logtypes.None,debugmode:!1,browsertype:mcafee_wa_browsertypes.Chrome,extnversion:"5.1.0.633",extensiontype:mcafee_wa_extensiontypes.Main},mcafee_wa_bkcommon=function(){return{toColor:function(a){var b=mcafee_wa_color.SA_Unknown;
return b=a<mcafee_wa_scorevals.ScoreMinimal?mcafee_wa_color.SA_Green:a<mcafee_wa_scorevals.ScoreUnknown?mcafee_wa_color.SA_Unknown:a<mcafee_wa_scorevals.ScoreMedium?mcafee_wa_color.SA_Yellow:mcafee_wa_color.SA_Red},isDisabled:function(a,b){for(var c=[{browser:mcafee_wa_browsertypes.Chrome,flag:mcafee_wa_disabledflags.disabledChrome},{browser:mcafee_wa_browsertypes.McAfeeSecureBrowser,flag:mcafee_wa_disabledflags.disabledSafeBrowser},{browser:mcafee_wa_browsertypes.Firefox,flag:mcafee_wa_disabledflags.disabledFirefox},
{browser:mcafee_wa_browsertypes.Edge,flag:mcafee_wa_disabledflags.disabledEdge},{browser:mcafee_wa_browsertypes.Opera,flag:mcafee_wa_disabledflags.disabledOpera}],d=0;d<c.length;++d)if(c[d].browser==b)return 0!=(c[d].flag&a)?!0:!1;return!1},isSiteAdvisorURL:function(a){return a.startsWith(mcafee_wa_bkconstants.siteAdvisorUrl)||a.startsWith(mcafee_wa_bkconstants.siteAdvisorUrlSecure)?!0:!1},isProperWebURL:function(a){return a.startsWith("http://")||a.startsWith("https://")||a.startsWith("ftp://")?
!0:!1},toStringExtensionType:function(a){return a==mcafee_wa_extensiontypes.Main?" (Main)":" (Search)"}}}(),storevariables={trustedsites:"trustedsites",searchoption:"searchoption"},mcafee_wa_store=function(){var a=function(a,b,c){var d={};d[a]=b;chrome.storage.local.set(d,c)},b=function(a,b){chrome.storage.local.get(a,function(c){b("undefined"==typeof c?null:c[a])})},c=function(a){b(storevariables.trustedsites,a)},d=function(a,b){if(null==a)return!1;for(var c=0;c<a.length;++c)if(a[c].toUpperCase()==
b.toUpperCase())return!0;return!1};return{set:a,get:b,remove:function(a){chrome.storage.local.remove(a)},getTrustedSites:c,isSiteTrusted:function(a,b){a=mcafee_wa_uriparser.getURI(a);c(function(c){null==c?b({trusted:!1}):d(c,a)?b({trusted:!0}):b({trusted:!1})})},addTrustedSite:function(b,f){b=mcafee_wa_uriparser.getURI(b);c(function(c){d(c,b)||(c=c?c:[],c.push(b),a(storevariables.trustedsites,c,function(){f({added:!0})}));f({added:!0})})},removeTrustedSite:function(b,d){b=mcafee_wa_uriparser.getURI(b);
c(function(c){if(null!=c){for(var g=[],k=0;k<c.length;++k)c[k].toUpperCase()!=b.toUpperCase()&&g.push(c[k]);a(storevariables.trustedsites,g,d)}})},getSearchOption:function(a){b(storevariables.searchoption,function(b){null==b&&(b=mcafee_wa_settings.browsertype==mcafee_wa_browsertypes.Chrome?mcafee_wa_searchoption.securesearch:mcafee_wa_searchoption.anysearch);a({option:b})})},setSearchOption:function(b){a(storevariables.searchoption,b)}}}();
function mcafee_wa_stats(){this.Type=Object.freeze({PagesScanned:0,PagesBlocked:1,ItemsBlocked:2});this.data={pagesScanned:0,pagesBlocked:0,itemsBlocked:0};this.read()}mcafee_wa_stats.prototype.add=function(a,b){"undefined"==typeof b&&(b=1);switch(a){case this.Type.PagesScanned:this.data.pagesScanned+=b;break;case this.Type.PagesBlocked:this.data.pagesBlocked+=b;break;case this.Type.ItemsBlocked:this.data.itemsBlocked+=b}this.save()};
mcafee_wa_stats.prototype.read=function(){var a=this;mcafee_wa_store.get("stats",function(b){"undefined"!=typeof b&&(a.data.pagesScanned=b.pagesScanned,a.data.pagesBlocked=b.pagesBlocked,a.data.itemsBlocked=b.itemsBlocked)})};mcafee_wa_stats.prototype.save=function(){mcafee_wa_store.set("stats",this.data)};mcafee_wa_stats.prototype.getData=function(){return this.data};
var mcafee_wa_bkglobals=function(){var a=new mcafee_wa_logger,b=new mcafee_wa_cache,c=new Map,d=new Map,e=new Map,f=mcafee_wa_annotationoptions.Unknown,h=new Map,g=new mcafee_wa_stats;return{isNewUserWelcomeDisabled:!1,messageDispatcher:null,activetabId:-1,logger:a,cache:b,options:c,blockPageMap:d,walite:null,pnaclFnMap:e,annotationOption:f,otherExtensionEnabled:!1,pnaclIdIter:0,searchURL:null,isChromeCompliant:!1,pnaclEnabled:0,pnaclInSearchEnabled:-1,isPProtectFeatureDisabled:!0,hasUserDisabledPProtect:!0,
idIter:0,callbackMap:h,featureStats:g,lastUrl:null,edgePort:null,isBingSecureSearchEnabled:!1,currentProvider:-1,requestHandler:null,webadvisorSupportedFeatures:null}}();function mcafee_wa_bknativelogger(){this._logTypes=mcafee_wa_logtypes.None}mcafee_wa_bknativelogger.prototype.SetLogTypes=function(a){this._logTypes=a};
mcafee_wa_bknativelogger.prototype.log=function(a){mcafee_wa_logtypes.Info&this._logTypes&&mcafee_wa_bkglobals.messageDispatcher.logMsg(16777216|mcafee_wa_bkglobals.browserType<<16|mcafee_wa_logtypes.Info,a)};mcafee_wa_bknativelogger.prototype.error=function(a){mcafee_wa_logtypes.Err&this._logTypes&&mcafee_wa_bkglobals.messageDispatcher.logMsg(16777216|mcafee_wa_bkglobals.browserType<<16|mcafee_wa_logtypes.Err,a)};
var mcafee_wa_browseraction=function(){return{disable:function(a){null!=chrome.browserAction&&"undefined"!=typeof chrome.browserAction&&chrome.browserAction.disable(a)},setTitle:function(a){null!=chrome.browserAction&&"undefined"!=typeof chrome.browserAction&&chrome.browserAction.setTitle({title:a})},setIcon:function(a,b,c){null!=chrome.browserAction&&"undefined"!=typeof chrome.browserAction&&(1==mcafee_wa_settings.debugmode&&mcafee_wa_bkglobals.logger.log("Setting browser action for url: "+c+" to image: "+
a),"undefined"!=typeof b?chrome.browserAction.setIcon({path:a,tabId:b}):chrome.browserAction.setIcon({path:a}))}}}();function mcafee_wa_csynchandler(){}mcafee_wa_csynchandler.prototype.cSyncHandler=function(a){if(null!=a){for(var b="",c="",d=0;d<a.length;d++)".doubleclick.net"==a[d].domain&&(b+=a[d].name+"="+a[d].value+"; "),".zeotap.com"==a[d].domain&&(c+=a[d].name+"="+a[d].value+"; ");if(0!=b.length)mcafee_wa_bkglobals.messageDispatcher.onCSync(b,c)}};
mcafee_wa_csynchandler.prototype.init=function(){setTimeout(function(){chrome.cookies.getAll({},function(a){mcafee_wa_csynchandler.prototype.cSyncHandler(a)})},6E4);setInterval(function(){chrome.cookies.getAll({},function(a){mcafee_wa_csynchandler.prototype.cSyncHandler(a)})},216E5)};
var mcafee_wa_dispatchwrap=function(){return{onBeforeNavigate:function(a,b,c,d){if(!mcafee_wa_extensionstatuschecker.isBlockPageDisabled())mcafee_wa_bkglobals.messageDispatcher.onBeforeNavigate(a,b,c,d)},onNavigate:function(a,b,c){if(!mcafee_wa_extensionstatuschecker.isBlockPageDisabled())mcafee_wa_bkglobals.messageDispatcher.onNavigate(a,b,c)},onDocComplete:function(a){if(!mcafee_wa_extensionstatuschecker.isBlockPageDisabled())mcafee_wa_bkglobals.messageDispatcher.onDocComplete(a)}}}(),mcafee_wa_extensionstatuschecker=
function(){var a=function(){return"ja"==window.navigator.language||"jp"==window.navigator.language||"ja_JP"==window.navigator.language};return{isJapanese:a,isBlockPageDisabled:function(){return mcafee_wa_settings.browsertype!=mcafee_wa_browsertypes.Chrome?!1:mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?!1:0==mcafee_wa_bkglobals.otherExtensionEnabled&&1==mcafee_wa_bkglobals.pnaclEnabled?!1:!0},isAnnotationDisabled:function(){return mcafee_wa_settings.browsertype!=mcafee_wa_browsertypes.Chrome?
!1:0==mcafee_wa_bkglobals.otherExtensionEnabled?mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?mcafee_wa_bkglobals.isChromeCompliant?mcafee_wa_bkglobals.annotationOption==mcafee_wa_annotationoptions.All||a()?!1:!0:!1:0==mcafee_wa_bkglobals.pnaclEnabled?!0:!1:mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?mcafee_wa_bkglobals.annotationOption==mcafee_wa_annotationoptions.All||a()?!1:1==mcafee_wa_bkglobals.pnaclInSearchEnabled?!0:!1:0==mcafee_wa_bkglobals.pnaclEnabled?
!0:mcafee_wa_bkglobals.annotationOption==mcafee_wa_annotationoptions.All||a()?!0:!1},initExtensionStatus:function(){chrome.management.getAll(function(a){chrome.management.getSelf(function(c){for(var d=0;d<a.length;++d){var e=a[d];if(e.id!=c.id&&mcafee_wa_supportedextensions.isExtensionSupported(e.id)){mcafee_wa_bkglobals.otherExtensionEnabled=e.enabled;break}}})})}}}();function mcafee_wa_managementlistener(){}
mcafee_wa_managementlistener.prototype.init=function(){chrome.management.onInstalled.addListener(function(a){});chrome.management.onUninstalled.addListener(function(a){mcafee_wa_supportedextensions.isExtensionSupported(a)&&(mcafee_wa_bkglobals.otherExtensionEnabled=!1)});chrome.management.onEnabled.addListener(function(a){mcafee_wa_supportedextensions.isExtensionSupported(a.id)&&(mcafee_wa_bkglobals.otherExtensionEnabled=!0)});chrome.management.onDisabled.addListener(function(a){mcafee_wa_supportedextensions.isExtensionSupported(a.id)&&
(mcafee_wa_bkglobals.otherExtensionEnabled=!1)})};function mcafee_wa_onchangeddownloadslistener(){}
mcafee_wa_onchangeddownloadslistener.prototype.init=function(){mcafee_wa_bkglobals.logger.log("adding download listener");try{mcafee_wa_settings.browsertype==mcafee_wa_browsertypes.Firefox?chrome.downloads.onCreated.addListener(function(a){var b=setInterval(function(){chrome.downloads.search({id:a.id},function(a){0==a.length&&clearInterval(b);var d=!1;a.forEach(function(a){"complete"==a.state?(mcafee_wa_bkglobals.logger.log("Firing download finished for item: "+a.filename),mcafee_wa_bkglobals.messageDispatcher.onDownloadFinished(a)):
"in_progress"==a.state&&(d=!0)});d||clearInterval(b)})},1E3)}):chrome.downloads.onChanged.addListener(function(a){try{mcafee_wa_bkglobals.logger.log("download event received"),null!=a&&null!=a.state&&"complete"==a.state.current&&(mcafee_wa_bkglobals.logger.log("download completed"),chrome.downloads.search({id:a.id},function(a){a.forEach(function(a){mcafee_wa_bkglobals.messageDispatcher.onDownloadFinished(a)})}))}catch(b){mcafee_wa_bkglobals.logger.error(b)}})}catch(a){mcafee_wa_bkglobals.logger.error(a)}};
function mcafee_wa_viewportsender(){}mcafee_wa_viewportsender.prototype.init=function(){setInterval(function(){mcafee_wa_bkglobals.messageDispatcher.getXYViewport()},3E3)};bingSecureSearch={isBingSecureSearch:1,donotKnow:0};function mcafee_wa_bingrequesthandler(){}
mcafee_wa_bingrequesthandler.prototype.process=function(a,b,c,d){null!=mcafee_wa_bkglobals.webadvisorSupportedFeatures&&1==mcafee_wa_bkglobals.webadvisorSupportedFeatures.honourssstatusfromextension&&this.isBingSecureSearch(d)&&(b|=2147483648);return{url:a,tabId:b,frameId:c}};
mcafee_wa_bingrequesthandler.prototype.isBingSecureSearch=function(a){var b=!1;mcafee_wa_bkglobals.currentProvider==mcafee_wa_bkconstants.BingProvider&&null!=a&&a.forEach(function(a){a.name==mcafee_wa_bkconstants.cookie&&a.value.split(";").forEach(function(a){-1!=a.indexOf(mcafee_wa_bkconstants.BingQString)&&(b=!0)})});return b};
var mcafee_wa_suitetype={issuite:1,isfreemium:2,isorphaned:4},mcafee_wa_blockpageuri=function(){var a=null;return{getBlockPageURI:function(b,c,d,e){var f=chrome.i18n.getUILanguage(),h=f.includes("_")?f.split("_"):f.split("-"),g=2==h.length?h[1]:f;null==a&&(a=new Map,a.set("US",{langval:"",frcode:"mcafee"}),a.set("AR",{langval:"ar.",frcode:"mcafee"}),a.set("AU",{langval:"au.",frcode:"mcafee"}),a.set("BR",{langval:"br.",frcode:"mcafee"}),a.set("CA",{langval:"ca.",frcode:"mcafee"}),a.set("FR",{langval:"fr.",
frcode:"mcafee"}),a.set("DE",{langval:"de.",frcode:"mcafee"}),a.set("HK",{langval:"hk.",frcode:"mcafee"}),a.set("IN",{langval:"in.",frcode:"mcafee"}),a.set("IT",{langval:"it.",frcode:"mcafee"}),a.set("KR",{langval:"kr.",frcode:"mcafee"}),a.set("MX",{langval:"mx.",frcode:"mcafee"}),a.set("ES",{langval:"es.",frcode:"mcafee"}),a.set("TW",{langval:"tw.",frcode:"mcafee"}),a.set("GB",{langval:"uk.",frcode:"mcafee"}),a.set("CF",{langval:"cf.",frcode:"mcafee"}),a.set("CL",{langval:"cl.",frcode:"mcafee"}),
a.set("CO",{langval:"co.",frcode:"mcafee"}),a.set("ID",{langval:"id.",frcode:"mcafee"}),a.set("NZ",{langval:"nz.",frcode:"mcafee"}),a.set("PE",{langval:"pe.",frcode:"mcafee"}),a.set("PH",{langval:"ph.",frcode:"mcafee"}),a.set("SG",{langval:"sg.",frcode:"mcafee"}),a.set("TH",{langval:"th.",frcode:"mcafee"}),a.set("E1",{langval:"espanol.",frcode:"mcafee"}),a.set("VE",{langval:"ve.",frcode:"mcafee"}),a.set("VN",{langval:"vn.",frcode:"mcafee"}),a.set("MY",{langval:"malaysia.",frcode:"mcafee"}),a.set("PT",
{langval:"",frcode:"mcafee_uninternational"}),a.set("BE",{langval:"",frcode:"mcafee_uninternational"}),a.set("NL",{langval:"nl.",frcode:"mcafee"}),a.set("DK",{langval:"dk.",frcode:"mcafee"}),a.set("FI",{langval:"fi.",frcode:"mcafee"}),a.set("NO",{langval:"no.",frcode:"mcafee"}),a.set("SE",{langval:"se.",frcode:"mcafee"}),a.set("CZ",{langval:"",frcode:"mcafee_uninternational"}),a.set("CH",{langval:"ch.",frcode:"mcafee"}),a.set("AT",{langval:"at.",frcode:"mcafee"}),a.set("GR",{langval:"",frcode:"mcafee_uninternational"}),
a.set("RU",{langval:"ru.",frcode:"mcafee_uninternational"}),a.set("PL",{langval:"pl.",frcode:"mcafee_uninternational"}),a.set("TR",{langval:"tr.",frcode:"mcafee_uninternational"}),a.set("HU",{langval:"",frcode:"mcafee_uninternational"}));var k=a.get(g);null==k&&(k=a.get("US"));h=new Date;b=encodeURIComponent(b);g=mcafee_wa_settings.browsertype.toString()+mcafee_wa_suitetype.isorphaned.toString()+g+"019700101";k=encodeURIComponent(mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?"https://"+
k.langval+"search.yahoo.com/search&type="+g:mcafee_wa_bkglobals.searchURL);g=mcafee_wa_settings.extnversion;if(mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Search){var l=g.indexOf(".");-1!=l&&(g="4"+g.substr(l))}d=(1==d?mcafee_wa_bkconstants.phishingPageUrl:mcafee_wa_bkconstants.blockPageUrl)+"?domain="+b+"&client_ver="+g+"&locale="+f+"&originalURL="+h.getTime();null!=k&&(d+="&searchurl="+k);mcafee_wa_bkglobals.blockPageMap.set(h.getTime().toString(),b);c&&(d+="&subframe=1");e(d);return!0}}}();
function mcafee_wa_webrequestlistener(){}
mcafee_wa_webrequestlistener.prototype.init=function(){chrome.webRequest.onCompleted.addListener(function(a){mcafee_wa_bkcommon.isSiteAdvisorURL(a.url)||(mcafee_wa_dispatchwrap.onNavigate(a.url,a.tabId,a.frameId),mcafee_wa_dispatchwrap.onDocComplete(a.url))},{urls:["http://*/*","https://*/*","ftp://*/*"],types:["main_frame","sub_frame"]});chrome.webRequest.onErrorOccurred.addListener(function(a){mcafee_wa_bkglobals.messageDispatcher.onNavigate(a.url,a.tabId,a.frameId)},{urls:["http://*/*","https://*/*"],
types:["main_frame"]});chrome.webRequest.onSendHeaders.addListener(function(a){if(!mcafee_wa_bkcommon.isSiteAdvisorURL(a.url))mcafee_wa_dispatchwrap.onBeforeNavigate(a.url,a.tabId,a.frameId,a.requestHeaders)},{urls:["http://*/*","https://*/*","ftp://*/*"],types:["main_frame","sub_frame"]},["requestHeaders"])};function mcafee_wa_pingsender(){}
mcafee_wa_pingsender.prototype.ping=function(a,b){chrome.runtime.sendMessage(a,{id:mcafee_wa_extensionmsgs.ping,pnaclenabled:mcafee_wa_bkglobals.pnaclEnabled},null,function(c){"undefined"!=typeof c&&"ping"==c?b.set(a,!0):b.set(a,!1);c=mcafee_wa_supportedextensions.getBuddyExtensions();for(var d=!1,e=0;e<c.length;++e)1==b.get(c[e])&&(d=!0);mcafee_wa_bkglobals.otherExtensionEnabled=d})};
mcafee_wa_pingsender.prototype.init=function(){var a=mcafee_wa_supportedextensions.getBuddyExtensions(),b=new Map,c=this;setInterval(function(){for(var d=0;d<a.length;++d)c.ping(a[d],b)},3E3)};function mcafee_wa_extensionmsglistener(){}
mcafee_wa_extensionmsglistener.prototype.init=function(){chrome.runtime.onMessageExternal.addListener(function(a,b,c){var d=!1;if(mcafee_wa_supportedextensions.isExtensionSupported(b.id))switch(a.id){case mcafee_wa_extensionmsgs.setoptionstring:mcafee_wa_bkglobals.annotationOption=a.option;break;case mcafee_wa_extensionmsgs.sendtelemetry:mcafee_wa_bkglobals.messageDispatcher.reportStat(a);break;case mcafee_wa_extensionmsgs.ping:"undefined"!=typeof a.pnaclenabled&&mcafee_wa_bkglobals.pnaclInSearchEnabled!=
a.pnaclenabled&&(mcafee_wa_bkglobals.pnaclInSearchEnabled=a.pnaclenabled,mcafee_wa_bkglobals.messageDispatcher.setSystemOptionString(mcafee_wa_bkconstants.pnaclenabled,mcafee_wa_bkglobals.pnaclInSearchEnabled.toString()));c("ping");d=!0;break;case mcafee_wa_extensionmsgs.syncoptionsfrommain:mcafee_wa_bkglobals.messageDispatcher.syncOptionsToSearchExt()}return d})};function mcafee_wa_tablistener(){}
mcafee_wa_tablistener.prototype.init=function(){chrome.tabs.onActivated.addListener(function(a){mcafee_wa_bkglobals.activetabId=a.tabId;mcafee_wa_bkglobals.options[mcafee_wa_bkconstants.disabled]&&mcafee_wa_browseraction.disable(a.tabId)});chrome.tabs.onCreated.addListener(function(a){mcafee_wa_bkglobals.options[mcafee_wa_bkconstants.disabled]?mcafee_wa_browseraction.disable(a.tabId):mcafee_wa_bkglobals.messageDispatcher.executeCommand(mcafee_wa_executecommands.raisenewtabevent,"")});chrome.tabs.onUpdated.addListener(function(a,
b,c){if("complete"==b.status&&"undefined"!=typeof c.url){b=mcafee_wa_bkglobals.lastUrl;if(null==b||b!=c.url)mcafee_wa_bkglobals.lastUrl=c.url,b="BrowserNavigate_"+mcafee_wa_browsertypefinder.browserTypeToString(mcafee_wa_bkglobals.browserType),mcafee_wa_bkglobals.messageDispatcher.reportStat({Name:b,Value:c.url});mcafee_wa_bkcommon.isSiteAdvisorURL(c.url)?(b=mcafee_wa_msgdispatchhelper.toQualifiedImagePath("small_button_hs.gif"),mcafee_wa_browseraction.setIcon(b,a,c.url)):mcafee_wa_bkcommon.isProperWebURL(c.url)||
(b=mcafee_wa_msgdispatchhelper.toQualifiedImagePath("small_button_disabled.gif"),mcafee_wa_browseraction.setIcon(b,a,c.url));mcafee_wa_settings.browsertype==mcafee_wa_browsertypes.Firefox&&mcafee_wa_bkcommon.isProperWebURL(c.url)&&mcafee_wa_bkglobals.messageDispatcher.executeCommand(mcafee_wa_executecommands.showwelcomemessage,"")}})};function mcafee_wa_onmessagelistener(){}
mcafee_wa_onmessagelistener.prototype.init=function(){try{chrome.runtime.onMessage.addListener(function(a,b,c){var d=!1;try{switch(a.command){case mcafee_wa_commands.ispageblocked:mcafee_wa_extensionstatuschecker.isBlockPageDisabled()||(d=mcafee_wa_bkglobals.messageDispatcher.isPageBlocked(a.Url,function(a,b){c({blocked:a,rediruri:b})}));break;case mcafee_wa_commands.dssrequest:d=mcafee_wa_bkglobals.messageDispatcher.makeDSSRequest(a.Url,a.searchEngineType,a.isSecureSearch,a.requestData,c);break;
case mcafee_wa_commands.reportstat:d=mcafee_wa_bkglobals.messageDispatcher.reportStat(a);break;case mcafee_wa_commands.executecommand:d=mcafee_wa_bkglobals.messageDispatcher.executeCommand(a.commandId,a.params);break;case mcafee_wa_commands.onnavigate:d=mcafee_wa_dispatchwrap.onBeforeNavigate(a.Url,b.tab.id,a.FrameId);d=mcafee_wa_dispatchwrap.onNavigate(a.Url,b.tab.id,a.FrameId);break;case mcafee_wa_commands.getsupportedfeatures:var e=mcafee_wa_supportedfeatures.none;mcafee_wa_bkglobals.options[mcafee_wa_bkconstants.disabled]||
(mcafee_wa_extensionstatuschecker.isAnnotationDisabled()||(e=mcafee_wa_supportedfeatures.annotations),mcafee_wa_extensionstatuschecker.isBlockPageDisabled()||(e=e|mcafee_wa_supportedfeatures.blockpages|mcafee_wa_supportedfeatures.iframeblocking),mcafee_wa_bkglobals.isPProtectFeatureDisabled||mcafee_wa_bkglobals.hasUserDisabledPProtect||(e|=mcafee_wa_supportedfeatures.pprotection));c({features:e,otherextensionenabled:mcafee_wa_bkglobals.otherExtensionEnabled});break;case mcafee_wa_commands.isframeblocked:mcafee_wa_bkglobals.messageDispatcher.isFrameBlocked(a.Url,
c);d=!0;break;case mcafee_wa_commands.logmsg:mcafee_wa_bkglobals.messageDispatcher.logMsg(a.logflags,a.message);break;case mcafee_wa_commands.getres:(new mcafee_wa_resourcerequestor).getResStr(a.resid,function(a){c(a)});d=!0;break;case mcafee_wa_commands.showoptions:mcafee_wa_bkglobals.messageDispatcher.onSettings(a.Url);break;case mcafee_wa_commands.addpagescanstat:mcafee_wa_bkglobals.featureStats.add(mcafee_wa_bkglobals.featureStats.Type.PagesScanned);break;case mcafee_wa_commands.getbingsecuresearchenabled:c(mcafee_wa_bkglobals.isBingSecureSearchEnabled),
d=!0}}catch(f){mcafee_wa_bkglobals.logger.error(f)}return d})}catch(a){mcafee_wa_bkglobals.logger.error(a)}};function mcafee_wa_legacynativemsgdispatcher(){this._port=0;this._callbackId=mcafee_wa_bkconstants.maxreservedcallbackid;this._messageMap={0:{}};this._contextMap={0:[null,-1]};this._viewport=null;this._icons=[];this._blockedFrames=new Map}mcafee_wa_legacynativemsgdispatcher.prototype.isPageBlocked=function(a,b){b(!1,null)};
mcafee_wa_legacynativemsgdispatcher.prototype.nativeMsg=function(a){var b=!1;try{var c=[1,0].concat(a),b=this.postMessage(c)}catch(d){return mcafee_wa_bkglobals.logger.error(d),!1}return b};mcafee_wa_legacynativemsgdispatcher.prototype.logMsg=function(a,b){try{this._port.postMessage([1,0,mcafee_wa_nativecommands.logmsg,a,b])}catch(c){}};
mcafee_wa_legacynativemsgdispatcher.prototype.postMessage=function(a){try{this._port.postMessage(a)}catch(b){return this._port.disconnect(),this._port=null,mcafee_wa_bkglobals.logger.error(b),!1}return!0};mcafee_wa_legacynativemsgdispatcher.prototype.addNewContext=function(a,b,c,d){this._contextMap[a]={req:b,url:c,topmost:d,refcount:1};return a};mcafee_wa_legacynativemsgdispatcher.prototype.urlFromContext=function(a){a=this._contextMap[a];if(null!=a&&"undefined"!=typeof a)return a.url};
mcafee_wa_legacynativemsgdispatcher.prototype.toTabId=function(a){a=parseInt(a);return isNaN(a)?-1:a=a<<16>>16&32767};mcafee_wa_legacynativemsgdispatcher.prototype.toFrameId=function(a){var b=parseInt(a);return isNaN(b)?-1:a>>16};
mcafee_wa_legacynativemsgdispatcher.prototype.navigateTab=function(a,b){var c=this.toFrameId(a),d=this.toTabId(a);mcafee_wa_bkglobals.logger.log("Navigate event received from native app for (tabid, frameId, uri) ,"+d+","+c+","+b);if(0==c)mcafee_wa_bkcommon.isSiteAdvisorURL(b)?(c={},c.url=b,chrome.tabs.update(d,c)):chrome.tabs.get(d,function(a){mcafee_wa_bkcommon.isSiteAdvisorURL(a.url)?(a={},a.url=b,chrome.tabs.update(d,a)):chrome.tabs.reload(d,{bypassCache:!0})});else{var e={};e.command=mcafee_wa_commands.onredirectiframe;
e.uri=b;var f=mcafee_wa_uriparser.getParam(b,"domain"),f=unescape(f);this._blockedFrames[f]=b;mcafee_wa_bkglobals.logger.log("Send Message to frame: "+c+" uri: "+b);chrome.tabs.sendMessage(d,e,function(a){"undefined"==typeof a&&"undefined "!=typeof chrome.runtime.lastError&&mcafee_wa_bkglobals.logger.error(chrome.runtime.lastError)})}};
mcafee_wa_legacynativemsgdispatcher.prototype.isFrameBlocked=function(a,b){var c=this._blockedFrames[a];mcafee_wa_bkglobals.logger.log("Checking whether iFrame is blocked for: "+a+". Status is : "+c);b({blocked:"undefined"!=typeof c,uri:c})};mcafee_wa_legacynativemsgdispatcher.prototype.toPageImage=function(a){return a>=this._icons.length?null:mcafee_wa_msgdispatchhelper.toQualifiedImagePath(this._icons[a])};
mcafee_wa_legacynativemsgdispatcher.prototype.setBrowserActionIcon=function(a,b){var c=this.toPageImage(a);null!=c&&chrome.tabs.get(b,function(a){mcafee_wa_browseraction.setIcon(c,b,a.url)})};mcafee_wa_legacynativemsgdispatcher.prototype.changeBrowserAction=function(a,b){if(0==this.toFrameId(a)){var c=this.toTabId(a);this.setBrowserActionIcon(b,c)}};
mcafee_wa_legacynativemsgdispatcher.prototype.processOption=function(a,b){mcafee_wa_bkglobals.options[a]=b;chrome.tabs.query({},function(c){for(var d={command:mcafee_wa_commands.onoptionreceived,optionName:a,optionValue:b},e=0;e<c.length;e++)chrome.tabs.sendMessage(c[e].id,d,null)})};
mcafee_wa_legacynativemsgdispatcher.prototype.getXYViewport=function(){var a={};a.command=mcafee_wa_commands.getxyviewport;var b=this;chrome.tabs.sendMessage(mcafee_wa_bkglobals.activetabId,a,function(a){if("undefined"==typeof a||null==a){if("undefined"!=typeof this._viewport&&null!=this._viewport)return;a={X:-1,Y:-1}}if(null==this._viewport||this._viewport.X!=a.X||this._viewport.Y!=a.Y){var d=a.X+","+a.Y;this._viewport=a;b.setSystemOptionString(mcafee_wa_bkconstants.viewport,d)}})};
mcafee_wa_legacynativemsgdispatcher.prototype.processInwardMssage=function(a){if(3>a.length)return-1==parseInt(a[0],10)&&(mcafee_wa_bkglobals.webadvisorSupportedFeatures=JSON.parse(a[1])),[];mcafee_wa_bkglobals.logger.log("Processing inward message: "+a[2]+" "+a[3]+" "+a[4]+" "+a[5]);switch(a[2]){case mcafee_wa_jscommands.addbitmap:return this._icons.push(a[3]),this._icons.length-1;case mcafee_wa_jscommands.changebitmap:this.changeBrowserAction(a[5],a[3]);break;case mcafee_wa_jscommands.navigate:this.navigateTab(a[5],
a[3]);break;case mcafee_wa_jscommands.urlfromcontext:return this.urlFromContext(a[3]);case mcafee_wa_jscommands.getxyviewport:return this.getXYViewport();case mcafee_wa_jscommands.refreshsettings:this.syncOptionsToSearchExt()}};
mcafee_wa_legacynativemsgdispatcher.prototype.syncOptionsToSearchExt=function(){var a=this;a.getSystemOptionBool(mcafee_wa_bkconstants.annonlyonssearch,!0,function(b){a.getSystemOptionBool(mcafee_wa_bkconstants.showicons,!0,function(a){mcafee_wa_bkglobals.annotationOption=a?b?mcafee_wa_annotationoptions.OnlySecureSearch:mcafee_wa_annotationoptions.All:mcafee_wa_annotationoptions.none;a=mcafee_wa_supportedextensions.getBuddyExtensions();for(var d=0;d<a.length;++d)chrome.runtime.sendMessage(a[d],{id:mcafee_wa_extensionmsgs.setoptionstring,
option:mcafee_wa_bkglobals.annotationOption})})})};
mcafee_wa_legacynativemsgdispatcher.prototype.listen=function(a){var b=this;this._port.onMessage.addListener(function(a){if(!(2>a.length)){var d=parseInt(a[0],10);if(d>mcafee_wa_bkconstants.maxreservedcallbackid){var e=b._messageMap[d];null!=e&&"undefined"!=typeof e&&(e.waPromise.resolve({response:a,callback:e.callback,promise:e.waPromise}),delete b._messageMap[d])}else d=b.processInwardMssage(a),b.postMessage([0,a[1],d])}});this._port.onDisconnect.addListener(function(){a({init:!1,disabled:!1})})};
mcafee_wa_legacynativemsgdispatcher.prototype.setSystemOptionString=function(a,b){return this.nativeMsg([mcafee_wa_nativecommands.setsystemoptionstring,a,b])};mcafee_wa_legacynativemsgdispatcher.prototype.getSystemOptionString=function(a,b,c){return this.makePromise(mcafee_wa_nativecommands.getsystemoptionstring,"undefined"==typeof c?null:c,[a,b])};
mcafee_wa_legacynativemsgdispatcher.prototype.getSystemOptionBool=function(a,b,c){return this.makePromise(mcafee_wa_nativecommands.getsystemoptionbool,"undefined"==typeof c?null:c,[a,b])};mcafee_wa_legacynativemsgdispatcher.prototype.getSystemOptionInt=function(a,b,c){return this.makePromise(mcafee_wa_nativecommands.getsystemoptionint,"undefined"==typeof c?null:c,[a,b])};
mcafee_wa_legacynativemsgdispatcher.prototype.init=function(a){try{this._port=chrome.runtime.connectNative("siteadvisor.mcafee.chrome.extension"),null!=this._port&&(this.listen(a),this.setSystemOptionString(mcafee_wa_bkconstants.browsertype,mcafee_wa_bkglobals.browserType.toString())&&this.setSystemOptionString(mcafee_wa_bkconstants.useragent,navigator.userAgent)&&(this.getSystemOptionBool(mcafee_wa_bkconstants.notchromecompliant,!0,function(a){mcafee_wa_bkglobals.isChromeCompliant=!a}),this.getSystemOptionBool(mcafee_wa_bkconstants.pprotectfeaturedisabled,
!1,function(a){mcafee_wa_bkglobals.isPProtectFeatureDisabled=a}),this.getSystemOptionBool(mcafee_wa_bkconstants.userdisabledpprotect,!1,function(a){mcafee_wa_bkglobals.hasUserDisabledPProtect=a}),this.nativeMsg([mcafee_wa_nativecommands.activate])&&(this.getSystemOptionString(mcafee_wa_bkconstants.disabled,"0",function(b){a({init:!0,disabled:b})}),this.syncOptionsToSearchExt(),this.getBingSecureSearchSettings())))}catch(b){return mcafee_wa_bkglobals.logger.error(b),!1}};
mcafee_wa_legacynativemsgdispatcher.prototype.uninit=function(){null!=this._port&&(this._port.disconnect(),this._port=null)};
mcafee_wa_legacynativemsgdispatcher.prototype.then=function(a){try{switch(a.promise.command){case mcafee_wa_nativecommands.getsystemoptionbool:var b=null==a.response[1]||a.response[1];a.promise.pThis.processOption(a.promise.commandParams[0],b);null!=a.callback&&a.callback(b);break;case mcafee_wa_nativecommands.getsystemoptionstring:a.promise.pThis.processOption(a.promise.commandParams[0],a.response[1]);null!=a.callback&&a.callback(a.response[1]);break;case mcafee_wa_nativecommands.getsystemoptionint:var c;
c="null"==a.response[1]?a.promise.commandParams[1]:a.response[1];a.promise.pThis.processOption(a.promise.commandParams[0],c);null!=a.callback&&a.callback(c);break;case mcafee_wa_nativecommands.ondssrequest:var d=JSON.parse(a.response[1]);a.callback(d)}}catch(e){mcafee_wa_bkglobals.logger.error(e)}};
mcafee_wa_legacynativemsgdispatcher.prototype.makePromise=function(a,b,c){var d=this,e=++this._callbackId,f=new mcafee_wa_promise,h=f.createPromise(function(b,f){var h=[1,e,a].concat(c);d.postMessage(h)},this.then,null,a,c,d);this._messageMap[e]={waPromise:f,callback:b};h.then(this.then);return!0};
mcafee_wa_legacynativemsgdispatcher.prototype.makeDSSRequest=function(a,b,c,d,e){a="dssrequest:multiquery/MultiQuery?tojson=1&href="+a+"&sourceType="+b+"&ssearch="+c;d=d.join("\t");return this.makePromise(mcafee_wa_nativecommands.ondssrequest,e,[a,d])};mcafee_wa_legacynativemsgdispatcher.prototype.onDownloadFinished=function(a){this.nativeMsg([mcafee_wa_nativecommands.ondownloadfinished,a.url,a.filename,null==a.referrer?"":a.referrer]);return!1};
mcafee_wa_legacynativemsgdispatcher.prototype.reportStat=function(a){mcafee_wa_bkglobals.logger.log("Stat: "+a.Name+" Value: "+a.Value);this.nativeMsg([mcafee_wa_nativecommands.reportstat,a.Name,"string"==typeof a.Value?a.Value:a.Value.toString()]);return!1};mcafee_wa_legacynativemsgdispatcher.prototype.onSettings=function(a){var b=this.generateContextId(mcafee_wa_bkglobals.activetabId,0);this.addNewContext(b,b,a,!0);this.nativeMsg([mcafee_wa_nativecommands.onMenuItemClick,114,b.toString()]);return!1};
mcafee_wa_legacynativemsgdispatcher.prototype.onDocComplete=function(a){this.nativeMsg([mcafee_wa_nativecommands.ondoccomplete,a,"",0,!0]);return!1};mcafee_wa_legacynativemsgdispatcher.prototype.generateContextId=function(a,b){return-1==b?a:a|b<<16};
mcafee_wa_legacynativemsgdispatcher.prototype.onBeforeNavigate=function(a,b,c,d){0>=c&&(delete this._blockedFrames,this._blockedFrames=new Map);d=mcafee_wa_bkglobals.requestHandler.process(a,b,c,d);var e=this.generateContextId(b,c);this.addNewContext(e,e,a,!0);mcafee_wa_bkglobals.logger.log("onBeforeNavigate event called for ( uri, tabId, frameid, contextid) ("+a+","+b+","+c+","+e+")");this.nativeMsg([mcafee_wa_nativecommands.onbeforenavigate,a,d.tabId.toString(),e.toString(),0==c]);return!1};
mcafee_wa_legacynativemsgdispatcher.prototype.onNavigate=function(a,b,c){var d=this.generateContextId(b,c);this.addNewContext(d,d,a,!0);mcafee_wa_bkglobals.logger.log("onNavigate event called for ( uri, tabId, frameid, contextid) ("+a+","+b+","+c+","+d+")");this.nativeMsg([mcafee_wa_nativecommands.onnavigate,a,d.toString(),d.toString(),0==c]);return!1};mcafee_wa_legacynativemsgdispatcher.prototype.executeCommand=function(a,b){this.nativeMsg([mcafee_wa_nativecommands.executecommand,a,b])};
mcafee_wa_legacynativemsgdispatcher.prototype.onCSync=function(a,b){this.nativeMsg([mcafee_wa_nativecommands.onCSync,navigator.userAgent,a,b])};
mcafee_wa_legacynativemsgdispatcher.prototype.getBingSecureSearchSettings=function(){var a=this;a.getSystemOptionString(mcafee_wa_bkconstants.SystemGEO,"",function(b){a.getSystemOptionString(mcafee_wa_bkconstants.BingCountrySet,"AU,DE",function(c){a.getSystemOptionInt(mcafee_wa_bkconstants.ProviderForced,-1,function(a){mcafee_wa_bkglobals.currentProvider=a;""!=b&&""!=c&&-1!=a&&c.split(",").includes(b)&&23==a&&(mcafee_wa_bkglobals.isBingSecureSearchEnabled=!0)})})})};
var mcafee_wa_listenermanager=function(){var a=[];return{getListeners:function(){0==a.length&&(a.push(new mcafee_wa_onmessagelistener),a.push(new mcafee_wa_tablistener),a.push(new mcafee_wa_webrequestlistener),mcafee_wa_bkglobals.browserType==mcafee_wa_browsertypes.Firefox?(a.push(new mcafee_wa_onchangeddownloadslistener),a.push(new mcafee_wa_viewportsender)):mcafee_wa_bkglobals.browserType==mcafee_wa_browsertypes.Chrome&&mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main&&a.push(new mcafee_wa_onchangeddownloadslistener),
mcafee_wa_bkglobals.browserType==mcafee_wa_browsertypes.Firefox&&a.push(new mcafee_wa_csynchandler),mcafee_wa_bkglobals.browserType==mcafee_wa_browsertypes.Chrome&&(a.push(new mcafee_wa_extensionmsglistener),a.push(new mcafee_wa_pingsender),mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Search&&a.push(new mcafee_wa_onbeforesendheaderlistener)));return a},getListenersWhenDisabled:function(){0==a.length&&(a.push(new mcafee_wa_tablistener),a.push(new mcafee_wa_onmessagelistener));return a}}}();
function mcafee_wa_background(){}mcafee_wa_background.prototype.processActiveTab=function(){chrome.tabs.query({active:!0},function(a){0!=a.length&&(mcafee_wa_bkglobals.activetabId=a[0].id,mcafee_wa_bkcommon.isProperWebURL(a[0].url)&&(mcafee_wa_dispatchwrap.onBeforeNavigate(a[0].url,a[0].id,0,null),mcafee_wa_dispatchwrap.onNavigate(a[0].url,a[0].id,0)))})};
mcafee_wa_background.prototype.handleDisabled=function(){mcafee_wa_bkglobals.messageDispatcher.uninit();for(var a=mcafee_wa_listenermanager.getListenersWhenDisabled(),b=0;b<a.length;++b)a[b].init();chrome.tabs.query({active:!0},function(a){0!=a.length&&mcafee_wa_browseraction.disable(a[0].tabId)})};mcafee_wa_background.prototype.handleEnabled=function(){for(var a=mcafee_wa_listenermanager.getListeners(),b=0;b<a.length;++b)a[b].init();this.processActiveTab()};
mcafee_wa_background.prototype.processInit=function(a){a=parseInt(a);a=mcafee_wa_bkcommon.isDisabled(a,mcafee_wa_bkglobals.browserType);(mcafee_wa_bkglobals.options[mcafee_wa_bkconstants.disabled]=a)?this.handleDisabled():this.handleEnabled()};
mcafee_wa_background.prototype.createDispatcher=function(){return mcafee_wa_settings.browsertype==mcafee_wa_browsertypes.Edge?new mcafee_wa_onlinemsgdispatcher(new mcafee_wa_edgemsgdispatcher):mcafee_wa_settings.browsertype==mcafee_wa_browsertypes.Chrome&&mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Search?new mcafee_wa_onlinemsgdispatcher(new mcafee_wa_pnaclmsgdispatcher):new mcafee_wa_legacynativemsgdispatcher};
mcafee_wa_background.prototype.main=function(){mcafee_wa_settings.loggertype==mcafee_wa_loggertype.nativeLogger&&(mcafee_wa_bkglobals.logger=new mcafee_wa_bknativelogger);mcafee_wa_bkglobals.logger.SetLogTypes(mcafee_wa_settings.logtype);mcafee_wa_bkglobals.options[mcafee_wa_bkconstants.disabled]=!1;mcafee_wa_bkglobals.browserType=mcafee_wa_browsertypefinder.getBrowserType(mcafee_wa_settings.browsertype);mcafee_wa_bkglobals.requestHandler=new mcafee_wa_bingrequesthandler;var a=this;mcafee_wa_bkglobals.messageDispatcher=
this.createDispatcher();mcafee_wa_bkglobals.messageDispatcher.init(function(b){1==b.init&&a.processInit(b.disabled)});mcafee_wa_settings.browsertype==mcafee_wa_browsertypes.Edge&&(mcafee_wa_bkglobals.edgePort=new mcafee_wa_edgeport)};var bkobj=new mcafee_wa_background;bkobj.main();
